os: Visual Studio 2015
clone_depth: 1

configuration:
  - Release

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%

build_script:
  - git submodule init
  - git submodule update
  - cd c:\projects\greatfet\libgreat\host\
  - C:\Python27-x64\python.exe setup.py build
  - C:\Python27-x64\python.exe setup.py install
  - cd ..\..\host\
  - C:\Python27-x64\python.exe setup.py build
  - C:\Python27-x64\python.exe setup.py install
  - cd c:\projects\greatfet\libgreat\host\
  - C:\Python37-x64\python.exe setup.py build
  - C:\Python37-x64\python.exe setup.py install
  - cd ..\..\host\
  - C:\Python37-x64\python.exe setup.py build
  - C:\Python37-x64\python.exe setup.py install